apiVersion: v1
kind: ConfigMap
metadata:
  name: liquidsoap-config
  namespace: radio
data:
  radio.liq: |
    music = mksafe(
      playlist(
        mode="random",
        reload=60,
        "/music/current/music"
      )
    )

    output.icecast(
      %ffmpeg(
        format="mp3",
        %audio(
          codec="libmp3lame",
          b="192k"
        )
      ),
      host="icecast.radio.svc.cluster.local",
      port=8000,
      password=environment.get("ICECAST_SOURCE_PASSWORD"),
      mount="/radio.mp3",
      name="NovaLabs Radio",
      description="NovaLabs Radio",
      genre="Various",
      public=false,
      music
    )
