apiVersion: v1
kind: ConfigMap
metadata:
  name: liquidsoap-config
  namespace: radio
data:
  radio.liq: |
    settings.prometheus.server := true
    settings.prometheus.server.port := 9599

    settings.frame.audio.samplerate := 48000

    playlist_source = playlist(
      id="radio_playlist",
      mode="random",
      reload=60,
      "/music/current/music"
    )

    music = mksafe(playlist_source)

    playlist_ready_metric = prometheus.gauge(
      labels=[],
      help="Whether the radio playlist source is ready.",
      "radio_playlist_ready"
    )

    set_playlist_ready = playlist_ready_metric(label_values=[])

    def update_playlist_ready() =
      if source.is_ready(playlist_source) then
        set_playlist_ready(1.)
      else
        set_playlist_ready(0.)
      end
    end

    thread.run(
      every=5.,
      update_playlist_ready
    )

    playlist_latency_metric = prometheus.latency(
      labels=[]
    )

    playlist_latency_metric(
      label_values=[],
      playlist_source
    )

    output.icecast(
      %ffmpeg(
        format="mp3",
        %audio(
          codec="libmp3lame",
          samplerate=48000,
          b="320k"
        )
      ),
      host="icecast.radio.svc.cluster.local",
      port=8000,
      password=environment.get("ICECAST_SOURCE_PASSWORD"),
      mount="/radio.mp3",
      name="NovaLabs Radio",
      description="NovaLabs Radio",
      genre="Various",
      public=false,
      music
    )
