apiVersion: v1
kind: Service
metadata:
  name: liquidsoap-metrics
  namespace: radio
  labels:
    app: liquidsoap
spec:
  selector:
    app: liquidsoap
  ports:
    - name: metrics
      port: 9599
      targetPort: metrics
