apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-music
  namespace: radio
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 60Gi
