apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/radio
  - storageclass.yaml
  - persistentvolume.yaml
  - icecast-auth.sops.yaml
  - ingress.yaml

patches:
  - path: storage.patch.yaml
