apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/radio
  - storageclass.yaml
  - persistentvolume.yaml
  - icecast-auth.sops.yaml
  - radio-library-ssh.sops.yaml
  - radio-tls.sops.yaml
  - ingress.yaml
  - certificate-production.yaml
  - ingress-public.yaml
  - library-sync-cronjob.yaml

patches:
  - path: storage.patch.yaml
