apiVersion: batch/v1
kind: CronJob
metadata:
  name: radio-library-sync
  namespace: radio

spec:
  schedule: "*/5 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        metadata:
          labels:
            app: radio-library-sync

        spec:
          restartPolicy: Never

          imagePullSecrets:
            - name: radio-registry-auth

          containers:
            - name: sync
              image: forgejo.caliconet.lab:3002/novalabs/lovelace-cluster/radio-library-sync@sha256:8857ffc7d9f028d9a46145ce62903d967aa0bc450ea60ad0b519a2f4261e9f1a
              imagePullPolicy: IfNotPresent

              volumeMounts:
                - name: music
                  mountPath: /library

                - name: ssh
                  mountPath: /ssh
                  readOnly: true

          volumes:
            - name: music
              persistentVolumeClaim:
                claimName: radio-music

            - name: ssh
              secret:
                secretName: radio-library-ssh
                defaultMode: 0400
