apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf
resources:
  - ../../base/audiobookshelf/
  - ingress.yaml
  - configmap.yaml
  - configmap.yaml
# patches:
# - path: deployment-env.patch.yaml
