apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf
resources:
  - ../../base/audiobookshelf/
  # - ingress.yaml # not in use right now, but can be used to expose linkding via traefik ingress
# patches:
# - path: deployment-env.patch.yaml
