apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:VI3ezIuHHmLTaifhVZUJcetupE5Q69hW7l55t1/43mj6jSTtpb/mBumqvstTuwIPEO440/RUCMdZ1d3m7OCpvjuI9Djpebjz2xL4/d4MSjD5rz+f0tPqbc6r5SOpffEPxMT+VkZ0gVzOfZPiPC1+HBLS8aJxfnbj/EQOcj3y+9EvJF06UboRtX8xJlH8dDhow288ddIw+LssBJ33jp9AKos8+1+WZpwq2IFaahg385AYaw5zUYSI/bPHtvqmMziOZd648zkCnGmnG5Al7wHm1AoVAaQhDFXmQWhZG3LjSggS0MWkjxfHzt4J4pQ=,iv:3kNxGNrtByITwjY02dtE0s9G55Iu4G4QqgqgzMufDnc=,tag:MGaQ3SgolG+Q2YZJ4ZluSw==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: audiobookshelf
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY1hxd1JKMWRqcjFXTkZM
        SkpuTXpIbEdTQ3pDYnFVdzNNSTVwN052K2hJCm9JZUtBb0hYKzVXeU1IQXVKZkJK
        UjR0SFpJZkVacnVOOFhncEU3Zk1wRFEKLS0tIDF5d0hqeHUrd2E5NjVWWXZObmxM
        UlJ1ZTNOeFp2dWN1UW83NEhLZjh1bFEKJWYoP04AUOBDUcv4OnrDEwW6I78WYZ5a
        7RKRqrGjqBi6hucCqi68K2VAFJWoY1Sfhl6U5kFphn/WYfpeH+gcJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T01:43:32Z"
  mac: ENC[AES256_GCM,data:l9YPNTzHSLu/mBxjOxRTmBbc32B3r1iMheh+Kmb2kdCXLcxMaa6lYafmVjEL4IZyIR4Sx3iCR3akoeE7dvkoA3d9ORvR3w1f0Op+b/b17DpwWH+OauERA6f96UNSDAcRoCY6tkqpQldDIiYiBbGLHG1gL4vyUTPa72BjRCKIpvg=,iv:VqIVQ9VkJKWyUqroRUdaRvHzHPy/ys21dUprz5citcw=,tag:+Aq/4MLr2TqrH0kcRMz/JA==,type:str]
  version: 3.13.3
