apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:8WWiKJqBAaNmFqq43D5+/ojp2SNrmvymLTwovPeKnBkmoQIONkjwSw+ZLSJCLJkCtltwPOf5ApovlwMhMqtyx02HKV5pa3b6OuNp0yNZV6G0DE6YxZrnP5boKn/4dTYhUFXV2+P9IPFPl+mL2fZ13rNB9jproy/mzEXCdFylRzPDlTpcp29GmEoxs3fpqrRiQac2ee372U2r0jEqMvpCGqYXpJ9627wNp0KR0o2HHydXSqqNC+uhKAAndDL3p7NEtwdcFyn5oPQ5THEvp9Rg4IVGWix5oWEA7Rrh1lhgJI34/HMoaohZVXapcQg=,iv:I3pWISXLOhPJQqqS8yWSWfD489xS9JUyvBGdGrB9otc=,tag:T2uEhwYKJZCUjwzwLm2hrw==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: audiobookshelf
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUEVWZjlNcStZWDNxL0ZG
        N0pzc0Nkdm1MYnQ0bC9RdTdJNkRwa0gzdTI0CkxGQTJBT3ZoRGhsQi9pd0x2Qlc3
        dG0rdDQ4SVpjalhES1FpTnJEWkdCY2sKLS0tIEFqc0dxK1g4MWw0alVQVGZVZGEy
        OXgya2drTWJBSXh3RlBXR1M4VjN3T0UK63albrl6tbM357lclkDU8JRMT/56IJdK
        uctr3Xmx0oWxUa8Qq7RjrAwSmVWVpL6j9Ya2+tCj1//IVo25karItQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T01:32:14Z"
  mac: ENC[AES256_GCM,data:bf11Kkis9g4TBsVFCCl/WIzOiehyuh/+bbk096sIoNpLP++FIA4BOgmj5EcBEh5vRyG3ItR4frDBdnJCZ1b/zTcAYdt8lgkVJqbHuRS7LRdbPK7XS+SvORhGglYrAlE3JnX/3+snAkOTUJzGif5QE4t6TbiPyCgC8FkPdJVwYgM=,iv:Vpv7aMMdA+sP/b3GpdKImD/ydGj2DXFIQaCwsfQJ1CY=,tag:Th0Pl9UIcJX2xWiDBUmxEQ==,type:str]
  version: 3.13.3
