apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: icecast
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - radio

  selector:
    matchLabels:
      app: icecast

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
