apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:2bgNeh1umNaqjEyqp9axDHZRSI0xXsKQPDSLHxlKOpedhkuUWAK2zZrpq4UEWRZZ6ouMJsRoyfoRfNDyrfCqUGQbJzDcSmmF,iv:OJLk5aRjHfdgv6Gl9ySGqQ9DBvbx92hOUPNY1huRZ4w=,tag:rYYqg7PGBmDGFgeaM24q9A==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK1dUdWQrVTU5eW1rRnZq
            T3A5OUFKbi9WOGNrdjZuS0sxOXU5bTJIQmxFCmhWYnBxSkxJc1B1UXBkWE1mRS8x
            RFVhVU0wOTMxM21zM3dMTkFmcHBTTkUKLS0tIDBMdUJDbC95WWVtdXdqMXJ2NmVr
            K25XR0NRQWtpTHEzVTgwOVpOTDZvb28KCfWamhlScZLz8VV381iNPzrWjPrbkjAz
            apk5ALUdMSQ5rLyvSEr3BrslqcrhMtfpawZ0qz2EAFgG2HFYNbI7ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T21:51:04Z"
    mac: ENC[AES256_GCM,data:i3xKKWdys1gqNej0bGRvJTEyq8SgY526PiOLLdUnJcT28JtqqQ3venUiKOZBZ/i6UGocOvrLuOfAFa2XPOq60EYYsrpLssReq6UIKiWoTPW+JePHJAaX9kMKaMOjILjqhDyp+viIt+MtQOZhaQ5AadwYDqvCUXFrJiKTkQ/MFkA=,iv:1lVg059Acjs9EDLWLxMj3GjmvZmp3GkwInsfl2llX5Q=,tag:XialKrq5n3lChCCSFnABrQ==,type:str]
    version: 3.13.2
