apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - tunnel-credentials.sops.yaml
  - linkding-superuser.sops.yaml
  # - ingress.yaml # not in use right now, but can be used to expose linkding via traefik ingress
patches:
  - path: deployment-env.patch.yaml
