apiVersion: v1
data:
  password: ENC[AES256_GCM,data:Ej6EX3yZqZI=,iv:C9jZbR8WsUmkWRBK+Tg0dM7lF2Olfh1qMhkMq2YI/74=,tag:FfrKbpuC5zUghogrpk5n0w==,type:str]
  user: ENC[AES256_GCM,data:l6KpVVs0oC0=,iv:1EePYNoiC0tUtxg9fjLW6J+l/vCM0KyIgw6j/AUhtpo=,tag:vUPZN0vR3Y2wGmtH1kxzaw==,type:str]
kind: Secret
metadata:
  name: test-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0hZaFJaazRkZmwwY0E4
        YWJ1dkFlQnhkQ2dlbTNaMDhUb0FXT3NIWkZvCjd1eXlsVmdSUmRGamNmZGVHY0tL
        MmZMakgrYVFkS200bCtyRXJPcGIzTTAKLS0tIFYwZVptVkExSi9UdnlvUTIvN1hC
        cXdiMEtnalhFVXErRURmWVl0K2hHZlEKQ2ZxGxS2TzlVnfXQddJjnvp1a9NSrWDR
        85bZeNU2wk4VS+/kEA/xOmkL1XstYjVVNZEqUi6gjvAZrbjqxeXlAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T17:51:21Z"
  mac: ENC[AES256_GCM,data:0Xs5SE8aQSn7zUIifgbXAascxBDLQaZo8eq2CrlzJ5hUpDut1HAv+AvYFRjDKZ19WaZhM7sM8qgggPHSbv2BT6KNH1QZ2tDFpy/cg2Xp4zMOLfiHmL7iGMeeHuq18MAdxclm5pZmyf7F3CpWHtPctFKWsaXSadT2fbmpoL2c1WM=,iv:/6Gs6l334NkU/SeLRfO4LvpPzyyQFMtdhZeUu31HWKM=,tag:bLslwNW6wKumYz1O8EQ2XA==,type:str]
  version: 3.13.3
