apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:crrQ8gyKsVjty9SxEf46n2UaRbKVHFENmoo/30NDbZu1vNA5L9WaaoTVS6maIfdwSR2VZdz8vsaI6P3xiXc0CI1hSXXyQ7769RiRm8Ab0BaQeWqa2eqfRinVx4kTvpn+CqiT2FZetUo24BfHViKzkSB2AExOMJa6x0HYQ8cwHjJp4VMD1mIrYkFoX4fwCplTxYK/NHPK66EPX5b4LX3vmAVGAm8WqIVZut8KDEuhk8q31rdG9ROghTHkB65gQn8vRwmBvRhO+A/J9EVfudsCcmKXP7M+FhmCFZoSYEYPtz5+JF/d2hiOs2wYKy0=,iv:FojAgHPAQgKgw0E78GiTt4ozA5jakZPiXUmjZq7bURg=,tag:9Af/0X28tQ5apJUpS8PYIA==,type:str]
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: linkding
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK1ZKempXcStLSi8zY0pD
        bnRFT01rTzRJYksrTTJRMENsRWpXOVFtSFRZCnJQQ2lyMTUxNjQyR1FhV2xzN2M3
        UFZWZW14S2hIMW00OWd6ZUdrVGZ5ZmsKLS0tIGlkYlNZais4MjhWcDJURVBwZlpO
        WElScnBPdHpnNzl6d2I1YlBaNURZVW8KlSL019/xBIBDJgPjH5vlSVOowkjtAmeq
        WIV1LiEhRDmfSr2BsP718/LnaFicBtzQjKi2cz+tIIXurY+xGF01aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T19:15:26Z"
  mac: ENC[AES256_GCM,data:AW/u/PCdn8rxSxG5d8RLjjqfEjilTlsG7OOjydZ2V0Cjsjy/IHWHvjUEdL56CFP/lMhZ8EoNkmLVPitzoKUWRjcu9pvKAOiDkKE6X0s8jEPSkOaBMLExLNWGawwtKvOFMB/VG4119T/5xgsfcxZahs2vbg9Agxg+zcEmqCk2Eoo=,iv:kDPMcbq0OXtDXcF8PaKkEd6HU2pdmaJfcVJx1CtVJLg=,tag:dgNMUkfYtHgKxgVj24GkRQ==,type:str]
  version: 3.13.3
