apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers # This Kustomization is responsible for deploying the monitoring controllers in the staging environment.
  namespace: flux-system
spec:
  interval: 1m0s
  #dependsOn:
  #  - name: infra-configs
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/controllers/staging # This path points to the directory in the Git repository where the manifests for the monitoring controllers are located.
  prune: true
  #decryption:
  #  provider: sops
  #  secretRef:
  #    name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs # This Kustomization is responsible for deploying the monitoring configurations in the staging environment.
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/configs/staging # This path points to the directory in the Git repository where the manifests for the monitoring configurations are located.
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
