apiVersion: v1
kind: Secret
metadata:
    name: playit-secret
    namespace: minecraft
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:rQpa2H/QSRHY6zx77UO/OYjA/bXNXVik+fUy31GYmS/nRuQ7IrlcLE5glFLGXfbqEoFFiNKiw6daxVV744OU3A==,iv:dfbJ3cpZrVmc4E8IwuXZBLhsMNiISnxFjuUW0nOvI5c=,tag:JpXJ2y+iLBftQ91vnr9CYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYzVaWE13RFN0bCtzV0p3
            eGlVVWt3MkRBSkZyMHlBeHdNOHZ4TjdiTEZnClBPcFlLOUdyR0pkR2hBZGtPQnZD
            M2QwMWRoQ0M0YmdtY3Z5UHFZWWR4M28KLS0tIDFpckNqdVgvUjl1S2F3NVl3dmJZ
            b2JUeWxnWlRiaXVkelFZdWNVTHlCbEUKbmoIGWMfIDbtlK4nKhnns0GmzO4r5fHB
            q6xREltUwGiVWqnFgbdiUIOtCPDJf8NwAh3U6jQ+y523Z3J5Drkzzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T18:06:22Z"
    mac: ENC[AES256_GCM,data:NtIFbAEHipy1nOyhMbNPftJyhGRvk9n9mmllolflKViY0dy3aK9ZmPKfDuMxZvgLS5lcNigGcd2buNUWG30lxG0iwivSibaArLG7axoxD/4fnF5lRjr4bh493hJhqG5xR/fjNRPaCqkytWer0eGfmqTrDEQBlCqCL2Glq5ymvj4=,iv:zr/73XcU9t/6RUiGU9hYVByouMbgGvmkAE38u4DTj4Q=,tag:aeQLrLi8EzqIty4XTr2uFw==,type:str]
    version: 3.13.2
