apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: minecraft-local
  resources:
    requests:
      storage: 60Gi
