apiVersion: v1
kind: Secret
metadata:
    name: minecraft-create-private
    namespace: minecraft-create
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:sUjPpMVU1K914Wa5MfvSN6WBcdmJob9nv3/pfb3uVDFpFkUkSiQRG1S6bHSOPn9o,iv:5SMPFvTueDype60cMsiXw3wdjeZZ0NGHCKyD6RaQmu8=,tag:ZXr6kVcikIUnC7X2ryuk3g==,type:str]
    SEED: ENC[AES256_GCM,data:AxutKVJtblUmNK3Zy13GCN9ybw==,iv:enwZDbfUjdlXyZWkKnXmT/pynfl/E5evM3wmDORgod4=,tag:jA9DmcjRGOrCob5VUE7Kjg==,type:str]
    WHITELIST: ENC[AES256_GCM,data:v7+SvanFD37ZEftYITBihPmMQZER3Bw8hMbS1U6AiKivHytO0Zd+qKF90rgs8BoTRljaurAJ31WaN6lyIKH6/BCXMgE9JY7Z,iv:i3omJg3S1zIsqQMwtKSKHSiSVRLMLH90r5PPIvtWrKU=,tag:z+nvmB2vYzgzupH9bz9UjA==,type:str]
    OPS: ENC[AES256_GCM,data:o1YWI0LBQ950SDJqyEKCtLWQ+hrzGRiV1RrOiEPnv4dM8ylEfgea,iv:P31w5TITUpZSy7g9SPqmJkSu+mMpxivOKqIjLqYxLK8=,tag:BFlVyiBVEvjCDTPArb2MnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdEtubVMrNHNtejNzeDBi
            MVdxSHlPNzBQc3VPZ2hYYkdoRkdyWi9kZTJrClR4M0tWTUxneUV0K2o5emFGQUhQ
            SXQxMVE3cEJ4QlFIOGV6dUlHUnkrdm8KLS0tIFlGd1BQTHpxRTNNakdXQ0NuZVVk
            cnlIczBMVjk1aXFUYWt2aG54N3M2elEKazaQhQ/aVOzQaXs+SIhkJk6v9bjX+aXh
            wdenULyCbkTiG7+FVWkHkRD8Ws30T6AXXupHpgFEZURUc6TNDze5gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T04:37:18Z"
    mac: ENC[AES256_GCM,data:akL5BiZ3gDxOTxMv/kjS2CpfmY35lPrnSN9uNWzKtmau2zamYSpOR6gkADl9bf6SQ/lscp1yIxeoFS8yz30EFC+sj4t4aYigu679kS+K9MGMTfASmI2zgc4FdRhGF8bg1D0tnygK0E4ZIzu0JGptrLX1r+a0EMIXk4833Qmgu98=,iv:EM8Tg+0ZuUxjMFEvi+Hnx2DosWHo992duZZZt2Ge+7Q=,tag:1V6i16gyep6SH86xSBdaoQ==,type:str]
    version: 3.13.3
