apiVersion: v1
kind: Secret
metadata:
    name: minecraft-create-private
    namespace: minecraft-create
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:5TopjqDF6xH2Y1Cea++sWxxIoV5i7mUdk8g8z1VQFrUrdK42EnSecGX8CM6oiVNX,iv:RetsAcAMu+aTv98UvJ+3zJmLvfeuxRvKMAiqzyMf8R0=,tag:JbIIbv6TGuoyXrkDHJq2Xg==,type:str]
    SEED: ENC[AES256_GCM,data:NSeU/IxHUkDX+dh9EgeI/APlHw==,iv:2GkT3F23er3Id+0lNJdHM1ZJDS+DDQtMvE3v+t36X2s=,tag:NoknIE3sjDSBE9WQxqj58A==,type:str]
    WHITELIST: ENC[AES256_GCM,data:+7ktpJbM7KMQ9C9cBbaopUOSQjTlc/E+KgTA9ZnLHjSvgYOUv93z/P6z+oKk2A==,iv:Yp51sSGoiRIS1/GJHb20Kbd2vqwGz5ChSKYtERDzSyE=,tag:ETmMW9o+qWPZzJmLLWOdxg==,type:str]
    OPS: ENC[AES256_GCM,data:qaLOPC6aSURQdsKkm2IWLYF19LPNhE46uAvIA2XP/HGzpzhlfzZ6,iv:B/hDQUjHIpn9zbsW+3D0II26paq4qa+ZZjtOakGU7t0=,tag:ZJchV0A0MOumpaoDXp6ARg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaWVIOG85ZXljNW5VZFRk
            Y2t4dUhuQ2hOQlB5Sm1ZWjltUUg0emx2dGhVCnlTTE9pNWZoVW9FZEwxdFhqelVM
            QWh5YWE3KzBEMlhmNEhOcDU1bGJ4UTgKLS0tIEVVWEwvRGk1NHlVSGFOaHhMQno5
            UlFQdWZRTXU0TzBRRlJTQlNLQ1VRaHcK/8QzrQv+cYEx77USTIZRkUa26ODokSIP
            bQNUsFjIWfyf9hEhMfqEZjSMQu3oAdlmtnC54V867ExKhWMUPskCmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T06:50:32Z"
    mac: ENC[AES256_GCM,data:oX7UmL3ENr192rCFs+aera0o45wFNOkSMxOsQ7uDLgY4IN1r1F+IVzTP5ZFxw//y6s1QGNRulLm7HZ9xIVQMv56LKBqmWu68AtzRAIRoZviEMO2NXvPwnImhlnWXLx4SaYzJ2kJ6tuLj19OD0mqdaLrCEKu7t9m/dQXbzpOBiRA=,iv:+RDZ8UhGlifb+wjQakiDAUYVrbSsxBxqoc/OCSCB2OU=,tag:DilJ7T9Ue3aNA3vxTeVFgw==,type:str]
    version: 3.13.2
