apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-create

resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - storage.yaml
  - storage-metrics.yaml
  - statefulset.yaml
# - playit.yaml

configMapGenerator:
  - name: minecraft-create-dh-metrics
    files:
      - collect-dh-metrics.py=dh-metrics.py
