apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-create-slow-day-cycle
  namespace: minecraft-create
data:
  pack.mcmeta: |
    {
      "pack": {
        "pack_format": 48,
        "description": "CalicoNet 8x slower day/night cycle"
      }
    }

  load.json: |
    {
      "values": [
        "caliconet_slow_time:load"
      ]
    }

  load.mcfunction: |
    gamerule doDaylightCycle false
    schedule function caliconet_slow_time:tick 8t replace

  tick.mcfunction: |
    time add 1
    schedule function caliconet_slow_time:tick 8t replace
