apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-create-data
  namespace: minecraft-create
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
