apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
  namespace: renovate
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_ENDPOINT: "http://forgejo.caliconet.lab:3002/api/v1/"
  RENOVATE_GIT_AUTHOR: "Lovelace Renovate Bot <renovate-bot@caliconet.lab>"
  RENOVATE_PLATFORM: "forgejo"
