apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid # will wait if a previous job is still running
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - NovaLabs/lovelace-cluster

              envFrom:
                - secretRef:
                    name: renovate-container-env
                - secretRef:
                    name: renovate-github-env
                - configMapRef:
                    name: renovate-configmap

          restartPolicy: Never
