apiVersion: v1
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DK8BYgg6nCBJ3/k3Guc+/fLN9LL5CBD8zrWd/d4He0maKIfydLzmPg==,iv:vcaCcN93V5db1oJLi1zmkTQStb4dK+OLXWxaZ4dl+zM=,tag:n3BU8PmtZo/zN6MQY21iMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJczJvRmdqb0EyRUx3UWky
            eFF3WVdpek9tLzc5VTM1M1E3YkVDWlV2SjJBCmxZVGRlZUFHV2taWUhMRG9sc2tN
            KzFkN0NsV09EUWZycU8vb0IxTFozeDQKLS0tIHVSajFhK2dqbUx1L3YvM2svTEJm
            RFlheXdhODlTUDNpbFVmZGZDU3RlK28Ke0n1fPY9H0ctTP5Z83oOuIWbVHVXgPZ3
            eys76N+rfbu8rJarMiP489+r0qaPEG8EE/jgjVrfDHpAo3WlH+oF7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jtcsfjakcl2pfnl78ss0l4dgfk0vyfdqel2u95x67p809c3eyfrs0u6xt2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T19:38:45Z"
    mac: ENC[AES256_GCM,data:4JAKUhqNiFmwk7ntN4dmaZ+M8qQVL7AedvdxfAW0Wvp6mzL+j2DnX3MXFwWo/rytUruxg7IYOtRFpTjsLpFsxp5IuxlA69uHMU2KirzW+anfWyh7RZO5gCIZrLHP3CQMto9fv+lu/OQ72uGqfpAaGYre7kWFlsLkWKh82inRz9w=,iv:qvtjsDhVBj+ZrS5PKiN4PkQMHFtthVokr5PRWo/iB8M=,tag:yD9lsSyVOiaF9IvihKykyA==,type:str]
    version: 3.13.2
